const INICIO = 'INICIO';
const DETALLE_JUGADOR = 'DETALLE_JUGADOR';
const CAROUSEL_JUGADOR = 'CAROUSEL_JUGADOR';

export const ROUTES = {
    INICIO,
    DETALLE_JUGADOR,
    CAROUSEL_JUGADOR: CAROUSEL_JUGADOR,
};
